### ISSUE TITLE
linux is disabled

### ISSUE THREAD

**Issue by looooo** [conda-forge/smesh-feedstock#1]
@conda-forge/core  any ideas why linux is disabled?
maybe this syntaxis not allowed? https://github.com/conda-forge/smesh-feedstock/blob/master/recipe/meta.yaml#L19
`skip: true  # [py<35 or win32 or osx]`

**Comment by jakirkham** [comment]
Normally this means that your requirements cannot be satisfied on Linux. Would explore this by trying to install them in an environment locally with `conda` and/or trying to build with `conda-build` to see where either of these approaches runs into problems.

**Comment by looooo** [comment]
@jakirkham it was working in the PR and also locally I am testing this package for a long time... (condaforge/linux-anvil)

**Comment by looooo** [comment]
re-rendering locally added linux again. I guess there went something wrong at the feedstock creation.
https://github.com/conda-forge/smesh-feedstock/pull/2

**Comment by looooo** [comment]
I would say it's more like 100%. Also in this case your suggestion was the initialization to find a solution.
thanks for the help!
