### ISSUE TITLE
set packages to broken

### ISSUE THREAD

**Issue by looooo** [conda-forge/smesh-feedstock#18]
@conda-forge/core 
please set the latest smesh-package to broken.
https://anaconda.org/conda-forge/smesh/files

![bildschirmfoto von 2019-01-15 15-13-57](https://user-images.githubusercontent.com/5084704/51185736-37391080-18d8-11e9-923d-48712f6e5dac.png)

**Comment by ocefpaf** [comment]
Done! Can you check: https://anaconda.org/conda-forge/smesh/files?version=8.3.0.2

**Comment by looooo** [comment]
@ocefpaf Thanks for having a look at this. Only the uppermost is broken ( linux-64/smesh-8.3.0.2-py36h5f0d5be_1.tar.bz2). The others are ok and should __not__ have the "broken" label. So it would be nice if you can remove the broken label from the lower 3 packages.

**Comment by looooo** [comment]
:+1: perfect thanks
