### ISSUE TITLE
how to port feedstock to new compilers

### ISSUE THREAD

**Issue by looooo** [conda-forge/smesh-feedstock#19]
@conda-forge/core 

Is the bot still creating migration PR's for new-compilers? If not is there still a way to do it manually?

**Comment by CJ-Wright** [comment]
The bot is still running (it just restarted the other day). You might need to wait on your dependents though. If everything is ready and you want to get a head start, you can put in build number bump with a rerender.

**Comment by looooo** [comment]
Thanks. Vtk seems to be the missing. I thought it is provided via defaults-channel but this is not true for python3.7.

**Comment by looooo** [comment]
vtk is not an easy one... Better to wait for the experts.

**Comment by looooo** [comment]
done
