### ISSUE TITLE
osx: missing Frameworks/Appkit.framework

### ISSUE THREAD

**Issue by looooo** [conda-forge/smesh-feedstock#6]
@jakirkham @scopatz 
building smesh on osx  fails because a mac-specific library seems to be missing. 
https://github.com/conda-forge/smesh-feedstock/pull/5

```
ninja: error: '/Applications/Xcode-9.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/Appkit.framework', needed by 'libSMESHMisc.dylib', missing and no known rule to make it
```

The error message says something about a missing `Appkit.framework` library. There is also a  warning about MACOSX_RPATH not set, but I don't know if this is related.
`MACOSX_RPATH is not specified for the following targets:`

The build-log can be found here:
https://travis-ci.org/conda-forge/smesh-feedstock/builds/380039136#L444

**Comment by scopatz** [comment]
Have you looked up this error online?  Have you tried switching CMake to use Make rather than Ninja?

**Comment by looooo** [comment]
@scopatz 
thanks for your help.

What I have tried so far:
- building occt with circle-ci which changed the error message: MacOSX10.13 -> MacOSX10.9
- building on circle ci

I will try to change ninja to make, although I don't think this can solve the problem.

**Comment by isuruf** [comment]
Try this, 
```bash
if [ `uname` = "Darwin" ]; then
    sed -i '' 's/Xcode-9.app/Xcode.app' $PREFIX/lib/cmake/opencascade/OpenCASCADEVisualizationTargets.cmake
fi
```

**Comment by isuruf** [comment]
Updated

**Comment by looooo** [comment]
great, that works! I am struggeling with understanding the fix. Should this be applied to the occt-feedstock? Is it a problem of occt or is it introduced by the path-fixing of the conda-build process?

**Comment by isuruf** [comment]
When exporting targets, cmake is hardcoding the location of the frameworks. occt was compiled in circle-ci and smesh was compiled in travis-ci where the osx sdk paths are different. I don't know how to fix it other than editing the cmake file to use `CONDA_BUILD_SYSROOT` if it's defined.

**Comment by looooo** [comment]
so switching smesh to circle-ci would make the fix obsolete...

thanks again, this was by far the most difficult problem with this recipe so far.

**Comment by jakirkham** [comment]
Should we try integrating this into `conda-forge-ci-setup` somehow?

**Comment by mingwandroid** [comment]
Appkit.framework is probably needed if it's linked here, it's not something likely to get dragged in by mistake, however `smesh`'s cmake stuff needs updating. Possibly all you need to do is pass:

```
-DCMAKE_MACOSX_SDK= /Applications/Xcode-9.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
```

@isuruf `CONDA_BUILD_SYSROOT` won't do anything outside of the `AD` compilers (and only then on macOS), but in general it should always hold the same value as `-DCMAKE_MACOSX_SDK`.
